using ETPlus;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using static ETPlus.AutoGenerateCodeEditor;

public class ScriptModifyEditor : AssetPostprocessor
{
    //模型导入之前调用
    public void OnPreprocessModel()
    {
        Debug.Log("OnPreprocessModel=" + this.assetPath);
    }

    //模型导入之前调用
    public void OnPostprocessModel(GameObject go)
    {
        Debug.Log("OnPostprocessModel=" + go.name);
    }

    //纹理导入之前调用，针对入到的纹理进行设置
    public void OnPreprocessTexture()
    {
        Debug.Log("OnPreProcessTexture=" + this.assetPath);
        TextureImporter impor = this.assetImporter as TextureImporter;
        impor.textureFormat = TextureImporterFormat.ARGB32;
        impor.maxTextureSize = 512;
        impor.textureType = TextureImporterType.Default;
        impor.mipmapEnabled = false;

    }

    public void OnPostprocessTexture(Texture2D tex)
    {
        //Debug.Log("OnPostProcessTexture=" + this.assetPath);
    }


    public void OnPostprocessAudio(AudioClip clip)
    {

    }

    //public void OnPreprocessAudio()
    //{
    //    AudioImporter audio = this.assetImporter as AudioImporter;
    //    audio.format = AudioImporterFormat.Compressed;
    //}

    //所有的资源的导入，删除，移动，都会调用此方法，注意，这个方法是static的
    public static void OnPostprocessAllAssets(string[] importedAsset, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
    {
        Debug.Log("OnPostprocessAllAssets");
        foreach (string assetPath in importedAsset)
        {
            var extension= Path.GetExtension(assetPath);

           // Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", extension, "test1"));

            switch (extension)
            {
                case ".cs":
                     var LastDir=Path.GetDirectoryName(assetPath);
                    var ParentFolderName = Path.GetFileNameWithoutExtension(LastDir);

                  //  Debug.Log(string.Format("<color=#ffffffff><--LastDir-{0}-{1}----></color>", LastDir, "test1"));

                    var root = Path.GetDirectoryName(LastDir);
                 
                    var  parentParentName= Path.GetFileName(root);

                    var fairyGUIFolder = Path.GetDirectoryName(root);


                    if (parentParentName== "AutoGeneratedCode")
                    {
                        var fileName = Path.GetFileNameWithoutExtension(assetPath);

                        var scriptContent = File.ReadAllText(assetPath);

                        var errorInfo = "ComponentFactory";
                        var fixedInfo = "EntityFactory";

                        var errorInfo2 = "GObject>(";
                        var fixedInfo2 = "GObject >(Game.Scene,";
                        
                        scriptContent= scriptContent.Replace(errorInfo, fixedInfo);

                        scriptContent = scriptContent.Replace(errorInfo2, fixedInfo2);

                        var Addcode= SplitContent2Code(scriptContent);


                        File.WriteAllText(assetPath, scriptContent);
                       


                        if (fileName.EndsWith("Component"))
                        {
                            var dirName= fairyGUIFolder + $@"\System\{ParentFolderName}\";
                            var sysFilePath =(dirName+$"{fileName}System.cs");
                            if (!File.Exists(sysFilePath))
                            {
                                 Directory.CreateDirectory(dirName);
                                AutoGenerateCodeEditor.AddCode = Addcode;

                                AutoGenerateCodeEditor.CreateScript(ScriptType.Component, $"{fileName}", sysFilePath, false);


                                Debug.Log(string.Format("<color=#ffffffff><---Addcode{0}-{1}----></color>", Addcode, "test1"));


                                AutoGenerateCodeEditor.AddCode = "";
                                //Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", sysFilePath, "test1"));

                            }

                            var realName = fileName.Replace("Component", "");

                            var eventdirName = fairyGUIFolder + $@"\System\{ParentFolderName}\";
                            var eventFilePath = (dirName + $"{realName}Event.cs");
                            if (!File.Exists(eventFilePath))
                            {
                                Directory.CreateDirectory(eventdirName);

                                AutoGenerateCodeEditor.CreateScript(ScriptType.Event, $"{realName}Event", eventFilePath, false);
                            }

                            var factDirName = fairyGUIFolder + $@"\System\{ParentFolderName}\";
                            var factFilePath = (dirName + $"{realName}Factory.cs");
                            if (!File.Exists(factFilePath))
                            {
                                Directory.CreateDirectory(factDirName);

                                AutoGenerateCodeEditor.CreateScript(ScriptType.Factory, $"{realName}Factory", factFilePath, false);
                            }

                           // Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", sysFilePath, fairyGUIFolder));
                            //Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", eventFilePath, fairyGUIFolder));


                        }

                        // File.WriteAllText()
                    }
                    //Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", root, "test1"));


                    
                    break;
                default:
                    break;
            }
           // Debug.Log("importedAsset = " + str);
        }
        foreach (string str in deletedAssets)
        {
            //Debug.Log("deletedAssets = " + str);
        }
        foreach (string str in movedAssets)
        {
           // Debug.Log("movedAssets = " + str);
        }
        foreach (string str in movedFromAssetPaths)
        {
           // Debug.Log("movedFromAssetPaths = " + str);
        }
        AssetDatabase.Refresh();
    }

    public static string SplitContent2Code(string content)
    {
        var start= content.IndexOf("public GComponent");

        var end = content.IndexOf("private static");
        if (start<=0|| end<=0)
        {
            return "";
        }
        var componentContent= content.Substring(start, end);

        Debug.LogError(string.Format("<color=#ff0000ff><---content{0}-{1}----></color>", componentContent, "test1"));

      //  string[] ContentLines = componentContent.Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);//不忽略空行
        var listenerCode = new StringBuilder();
        var TextCode = new StringBuilder();

        var methodCode = new StringBuilder();

       // Debug.LogError(string.Format("<color=#ff0000ff><---{0}-{1}----></color>", ContentLines.Length, "test1"));
        using (StringReader sr = new StringReader(componentContent))
        {
            string line;
            int lineIndex = 0;
            while ((line = sr.ReadLine()) != null)
            {
                var values = line.Split(' ', ';');
                if (values.Length < 3)
                {
                    continue;
                }
                // Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", line, "test1"));

                //for (int j = 0; j < values.Length; j++)
                //{
                //    var val=values[j];

                //    Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", val, "test1"));

                //}
                // Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", startCom, endCom - 1));

                var comNmae = values[2];

                Debug.Log(string.Format("<color=#ffffffff><---{0}-{1}----></color>", comNmae, "test1"));

                if (line.EndsWith("Btn;"))
                {
                    listenerCode.AppendLine();
                    listenerCode.AppendLine($@"		    self.{comNmae}.self.onClick.Add(On{comNmae}Click);");

                    TextCode.AppendLine();

                    methodCode.AppendLine($@"		    void On{comNmae}Click()");
                    methodCode.AppendLine("		    {");
                    methodCode.AppendLine();
                    methodCode.AppendLine("		    }");

                }

                if (line.EndsWith("In;"))
                {
                    TextCode.AppendLine();
                    TextCode.AppendLine($@"		    var {comNmae}Content= self.{comNmae}.text;");

                }
                if (line.EndsWith("Controller;"))
                {
                    TextCode.AppendLine();
                    TextCode.AppendLine($@"		    var {comNmae}= self.{comNmae};");

                }
            }
        }
            
            var fieldCode= TextCode.ToString() + listenerCode.ToString();
        fieldCode = "\n#region FieldCode \n" + fieldCode+ "\n #endregion\n";

        var EndmethodCode = "\n#region MethodCode \n" + methodCode + "\n #endregion\n";


        return fieldCode + EndmethodCode;

    }
}
